# Generated by Django 4.1.2 on 2022-11-09 04:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=300, null=True, verbose_name='Client Name')),
                ('report_date', models.DateField(null=True, verbose_name='Report Date')),
                ('effective_date', models.DateField(null=True, verbose_name='Effective Date')),
                ('ref_code', models.CharField(max_length=300, null=True, verbose_name='Ref Code')),
                ('firstname', models.CharField(max_length=300, null=True, verbose_name='First Name')),
                ('lastname', models.CharField(max_length=300, null=True, verbose_name='Last Name')),
                ('email', models.CharField(max_length=300, null=True, verbose_name='Email Address')),
                ('phone_number', models.CharField(max_length=300, null=True, verbose_name='Phone Number')),
                ('location', models.TextField(max_length=300, null=True, verbose_name='Location')),
                ('municipal_address', models.TextField(max_length=300, null=True, verbose_name='Municipal Address')),
                ('site_area', models.FloatField(null=True, verbose_name='Site Area(Sqr. Ft.)')),
                ('latitude', models.FloatField(null=True, verbose_name='Latitude')),
                ('longitude', models.FloatField(null=True, verbose_name='Longitude')),
                ('dropdown_feature', models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C')], null=True, verbose_name='Dropdown Feature')),
                ('textarea1', models.TextField(max_length=300, null=True, verbose_name='TextArea 1')),
                ('textarea2', models.TextField(max_length=300, null=True, verbose_name='TextArea 2')),
                ('textarea3', models.TextField(max_length=300, null=True, verbose_name='TextArea 3')),
                ('radio_button_feature', models.IntegerField(choices=[(1, 'select 1'), (2, 'select 2'), (3, 'select 3')], null=True, verbose_name='Radio Button Feature')),
                ('receive_newsletter', models.BooleanField(null=True, verbose_name='Receive NewsLetter')),
                ('fpdf', models.FileField(null=True, upload_to='reports/%Y/%m/%d/', verbose_name='Report File')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('photo', models.ImageField(blank=True, upload_to='users/%Y/%m/%d/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
