# Generated by Django 4.1 on 2022-10-26 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Client Name",
                    ),
                ),
                (
                    "report_date",
                    models.DateField(blank=True, null=True, verbose_name="Report Date"),
                ),
                (
                    "effective_date",
                    models.DateField(
                        blank=True, null=True, verbose_name="Effective Date"
                    ),
                ),
                (
                    "ref_code",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="Ref Code"
                    ),
                ),
                (
                    "firstname",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="First Name"
                    ),
                ),
                (
                    "lastname",
                    models.CharField(
                        blank=True, max_length=300, null=True, verbose_name="Last Name"
                    ),
                ),
                (
                    "email",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Email Address",
                    ),
                ),
                (
                    "phone_number",
                    models.CharField(
                        blank=True,
                        max_length=300,
                        null=True,
                        verbose_name="Phone Number",
                    ),
                ),
                (
                    "location",
                    models.TextField(
                        blank=True, max_length=300, null=True, verbose_name="Location"
                    ),
                ),
                (
                    "latitude",
                    models.FloatField(blank=True, null=True, verbose_name="Latitude"),
                ),
                (
                    "longitude",
                    models.FloatField(blank=True, null=True, verbose_name="Longitude"),
                ),
                (
                    "dropdown_feature",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "A"), (2, "B"), (3, "C")],
                        null=True,
                        verbose_name="Dropdown Feature",
                    ),
                ),
                (
                    "textarea1",
                    models.TextField(
                        blank=True, max_length=300, null=True, verbose_name="TextArea 1"
                    ),
                ),
                (
                    "textarea2",
                    models.TextField(
                        blank=True, max_length=300, null=True, verbose_name="TextArea 2"
                    ),
                ),
                (
                    "textarea3",
                    models.TextField(
                        blank=True, max_length=300, null=True, verbose_name="TextArea 3"
                    ),
                ),
                (
                    "radio_button_feature",
                    models.IntegerField(
                        blank=True,
                        choices=[(1, "select 1"), (2, "select 2"), (3, "select 3")],
                        null=True,
                        verbose_name="Radio Button Feature",
                    ),
                ),
                (
                    "receive_newsletter",
                    models.BooleanField(
                        blank=True, null=True, verbose_name="Receive NewsLetter"
                    ),
                ),
                (
                    "fpdf",
                    models.FileField(
                        blank=True,
                        null=True,
                        upload_to="reports/%Y/%m/%d/",
                        verbose_name="Report File",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Profile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date_of_birth", models.DateField(blank=True, null=True)),
                ("photo", models.ImageField(blank=True, upload_to="users/%Y/%m/%d/")),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
