# Generated by Django 4.1.2 on 2022-11-07 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='municipal_address',
            field=models.TextField(max_length=300, null=True, verbose_name='Municipal Address'),
        ),
        migrations.AlterField(
            model_name='report',
            name='client_name',
            field=models.CharField(max_length=300, null=True, verbose_name='Client Name'),
        ),
        migrations.AlterField(
            model_name='report',
            name='dropdown_feature',
            field=models.IntegerField(choices=[(1, 'A'), (2, 'B'), (3, 'C')], null=True, verbose_name='Dropdown Feature'),
        ),
        migrations.AlterField(
            model_name='report',
            name='effective_date',
            field=models.DateField(null=True, verbose_name='Effective Date'),
        ),
        migrations.AlterField(
            model_name='report',
            name='email',
            field=models.CharField(max_length=300, null=True, verbose_name='Email Address'),
        ),
        migrations.AlterField(
            model_name='report',
            name='firstname',
            field=models.CharField(max_length=300, null=True, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='report',
            name='fpdf',
            field=models.FileField(null=True, upload_to='reports/%Y/%m/%d/', verbose_name='Report File'),
        ),
        migrations.AlterField(
            model_name='report',
            name='lastname',
            field=models.CharField(max_length=300, null=True, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='report',
            name='latitude',
            field=models.FloatField(null=True, verbose_name='Latitude'),
        ),
        migrations.AlterField(
            model_name='report',
            name='location',
            field=models.TextField(max_length=300, null=True, verbose_name='Location'),
        ),
        migrations.AlterField(
            model_name='report',
            name='longitude',
            field=models.FloatField(null=True, verbose_name='Longitude'),
        ),
        migrations.AlterField(
            model_name='report',
            name='phone_number',
            field=models.CharField(max_length=300, null=True, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='report',
            name='radio_button_feature',
            field=models.IntegerField(choices=[(1, 'select 1'), (2, 'select 2'), (3, 'select 3')], null=True, verbose_name='Radio Button Feature'),
        ),
        migrations.AlterField(
            model_name='report',
            name='receive_newsletter',
            field=models.BooleanField(null=True, verbose_name='Receive NewsLetter'),
        ),
        migrations.AlterField(
            model_name='report',
            name='ref_code',
            field=models.CharField(max_length=300, null=True, verbose_name='Ref Code'),
        ),
        migrations.AlterField(
            model_name='report',
            name='report_date',
            field=models.DateField(null=True, verbose_name='Report Date'),
        ),
        migrations.AlterField(
            model_name='report',
            name='textarea1',
            field=models.TextField(max_length=300, null=True, verbose_name='TextArea 1'),
        ),
        migrations.AlterField(
            model_name='report',
            name='textarea2',
            field=models.TextField(max_length=300, null=True, verbose_name='TextArea 2'),
        ),
        migrations.AlterField(
            model_name='report',
            name='textarea3',
            field=models.TextField(max_length=300, null=True, verbose_name='TextArea 3'),
        ),
    ]
