# Generated by Django 4.1.2 on 2022-11-20 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='report',
            name='dropdown_feature',
        ),
        migrations.RemoveField(
            model_name='report',
            name='email',
        ),
        migrations.RemoveField(
            model_name='report',
            name='firstname',
        ),
        migrations.RemoveField(
            model_name='report',
            name='fpdf',
        ),
        migrations.RemoveField(
            model_name='report',
            name='lastname',
        ),
        migrations.RemoveField(
            model_name='report',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='report',
            name='location',
        ),
        migrations.RemoveField(
            model_name='report',
            name='longitude',
        ),
        # migrations.RemoveField(
        #     model_name='report',
        #     name='municipal_address',
        # ),
        migrations.RemoveField(
            model_name='report',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='report',
            name='radio_button_feature',
        ),
        migrations.RemoveField(
            model_name='report',
            name='receive_newsletter',
        ),
        migrations.RemoveField(
            model_name='report',
            name='ref_code',
        ),
        migrations.RemoveField(
            model_name='report',
            name='report_date',
        ),
        migrations.RemoveField(
            model_name='report',
            name='textarea1',
        ),
        migrations.RemoveField(
            model_name='report',
            name='textarea2',
        ),
        migrations.RemoveField(
            model_name='report',
            name='textarea3',
        ),
        migrations.AddField(
            model_name='report',
            name='abutting_streets',
            field=models.TextField(null=True, verbose_name='Abutting streets'),
        ),
        migrations.AddField(
            model_name='report',
            name='appraisal_type',
            field=models.CharField(max_length=255, null=True, verbose_name='Appraisal type'),
        ),
        migrations.AddField(
            model_name='report',
            name='appraiser_name_and_credentials',
            field=models.CharField(max_length=255, null=True, verbose_name='Appraiser name & credentials'),
        ),
        migrations.AddField(
            model_name='report',
            name='appraiser_sign',
            field=models.ImageField(null=True, upload_to='uploads/', verbose_name='Appraiser Signature'),
        ),
        migrations.AddField(
            model_name='report',
            name='client_address',
            field=models.CharField(max_length=255, null=True, verbose_name='Client address'),
        ),
        migrations.AddField(
            model_name='report',
            name='client_legal_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Client legal name'),
        ),
        migrations.AddField(
            model_name='report',
            name='current_improvement',
            field=models.TextField(null=True, verbose_name='Current Improvements'),
        ),
        migrations.AddField(
            model_name='report',
            name='file_no',
            field=models.CharField(max_length=255, null=True, verbose_name='File No.'),
        ),
        migrations.AddField(
            model_name='report',
            name='highest_best_use',
            field=models.TextField(null=True, verbose_name='Highest best use'),
        ),
        migrations.AddField(
            model_name='report',
            name='legal_description',
            field=models.TextField(null=True, verbose_name='Legal description'),
        ),
        migrations.AddField(
            model_name='report',
            name='market_value_estimate',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Market value estimate'),
        ),
        migrations.AddField(
            model_name='report',
            name='pin_no',
            field=models.CharField(max_length=255, null=True, verbose_name='Pin No.'),
        ),
        migrations.AddField(
            model_name='report',
            name='price_per_sq_ft',
            field=models.DecimalField(decimal_places=2, max_digits=10, null=True, verbose_name='Price per sqr. ft.'),
        ),
        migrations.AddField(
            model_name='report',
            name='proposed_development',
            field=models.TextField(null=True, verbose_name='Proposed development'),
        ),
        migrations.AddField(
            model_name='report',
            name='purpose',
            field=models.CharField(max_length=255, null=True, verbose_name='Purpose'),
        ),
        migrations.AddField(
            model_name='report',
            name='report_completion_date',
            field=models.DateField(null=True, verbose_name='Report completion date'),
        ),
        migrations.AddField(
            model_name='report',
            name='subject_property',
            field=models.CharField(max_length=255, null=True, verbose_name='Subject Property'),
        ),
        migrations.AddField(
            model_name='report',
            name='zoning',
            field=models.CharField(max_length=255, null=True, verbose_name='Zoning'),
        ),
        migrations.AlterField(
            model_name='report',
            name='client_name',
            field=models.CharField(max_length=255, null=True, verbose_name='Client name'),
        ),
        migrations.AlterField(
            model_name='report',
            name='effective_date',
            field=models.DateField(null=True, verbose_name='Effective Date/Insepction date'),
        ),
    ]
