# Generated by Django 4.1.2 on 2022-11-07 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_report_municipal_address_alter_report_client_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='site_area',
            field=models.FloatField(null=True, verbose_name='Site Area(Sqr. Ft.)'),
        ),
    ]
