# Generated by Django 4.1 on 2022-11-05 08:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_report_user_alter_report_client_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(model_name="report", name="user",),
    ]
